"""restore candidates table

Revision ID: 5f045835f533
Revises: 8c8751ec8ba2
Create Date: 2026-07-06 18:11:09.615721
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f045835f533'
down_revision: Union[str, None] = '8c8751ec8ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_filename', sa.String(length=500), nullable=True),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('experience_json', sa.Text(), nullable=True),
    sa.Column('education_json', sa.Text(), nullable=True),
    sa.Column('certifications_json', sa.Text(), nullable=True),
    sa.Column('languages_json', sa.Text(), nullable=True),
    sa.Column('projects_json', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('missing_skills_json', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('interview_questions_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
